#!/usr/bin/env python3
"""Generate each program's literature/REFERENCES.md from the per-paper cards.

Deterministic: output depends only on the card files on disk (sorted). Mirrors build_research_index.py.

    python org_frontier/research/build_cards_index.py          # rewrite every REFERENCES.md
    python org_frontier/research/build_cards_index.py --check   # exit 1 if any REFERENCES.md is stale
"""
import glob
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROGRAMS = ["computational", "field", "qualitative", "recurrence", "survey", "cognition"]


def frontmatter(path):
    """Parse the leading YAML-ish frontmatter of a card into a flat dict (scalars only)."""
    fm = {}
    with open(path, encoding="utf-8") as f:
        text = f.read()
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return fm
    for line in m.group(1).splitlines():
        mm = re.match(r"([A-Za-z_]+):\s*(.*)$", line)
        if mm:
            fm[mm.group(1)] = mm.group(2).strip()
    return fm


def cards(base):
    return sorted(glob.glob(os.path.join(base, "literature", "cards", "*.md")))


def build_one(program):
    base = os.path.join(HERE, program)
    cs = cards(base)
    L = [f"# {program} — reference cards", "",
         "*Generated by `build_cards_index.py`. Do not edit by hand — edits are overwritten.*", "",
         "Per-paper annotation cards: summary, key facts, critical notes, and topics, each grounded in the "
         "paper's open-access full text. PDFs are gitignored; see "
         "[`pdfs.manifest.json`](pdfs.manifest.json) for acquisition status of every reference.", ""]
    if not cs:
        L += ["*No cards yet.*", ""]
        return "\n".join(L).rstrip() + "\n"
    L += [f"**{len(cs)} cards.**", "", "| citekey | title | year | status | verified | card |",
          "|---|---|---|---|---|---|"]
    for c in cs:
        fm = frontmatter(c)
        ck = fm.get("citekey", os.path.basename(c)[:-3])
        title = (fm.get("title", "") or "").replace("|", "\\|")
        if len(title) > 90:
            title = title[:87] + "…"
        year = fm.get("year", "—")
        status = fm.get("pdf_status", "—")
        ver = fm.get("verified", "—")
        rel = f"cards/{os.path.basename(c)}"
        L.append(f"| {ck} | {title} | {year} | {status} | {ver} | [card]({rel}) |")
    L.append("")
    return "\n".join(L).rstrip() + "\n"


def targets():
    out = []
    for p in PROGRAMS:
        base = os.path.join(HERE, p)
        cdir = os.path.join(base, "literature", "cards")
        if os.path.isdir(cdir):
            out.append((os.path.join(base, "literature", "REFERENCES.md"), build_one(p)))
    return out


def main():
    check = "--check" in sys.argv
    stale = []
    for path, content in targets():
        if check:
            existing = open(path).read() if os.path.exists(path) else ""
            if existing != content:
                stale.append(path)
        else:
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"Wrote {path}")
    if check:
        if stale:
            print("stale REFERENCES.md — run build_cards_index.py:\n  " + "\n  ".join(stale))
            sys.exit(1)
        print("REFERENCES.md files up to date.")


if __name__ == "__main__":
    main()
