#!/usr/bin/env python3
"""Generate org_frontier/research/INDEX.md from the program and topic directories.

Deterministic: the output depends only on the files on disk (all lists sorted). Mirrors the conventions of
tools/build_index.py (first heading, first paragraph, clip). Run from anywhere:

    python org_frontier/research/build_research_index.py          # rewrite INDEX.md
    python org_frontier/research/build_research_index.py --check   # exit 1 if INDEX.md is stale
"""

import glob
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROGRAMS = ["computational", "field", "qualitative", "recurrence", "survey", "cognition"]
META_RE = re.compile(r"<!--\s*run:\s*([0-9-]+)\s*\|\s*sources:\s*(\d+)\s*\|\s*verified:\s*(\d+)")


def first_heading(path):
    if not os.path.exists(path):
        return None
    with open(path) as f:
        for line in f:
            if line.startswith("# "):
                return line[2:].strip()
    return None


def count_bib(path):
    if not os.path.exists(path):
        return 0
    with open(path) as f:
        return len(re.findall(r"^@\w+\s*\{", f.read(), re.M))


def meta(path):
    """The (run-date, sources, verified) from a report's leading metadata comment, or (None, 0, 0)."""
    if not os.path.exists(path):
        return (None, 0, 0)
    with open(path) as f:
        head = f.read(400)
    m = META_RE.search(head)
    if m:
        return (m.group(1), int(m.group(2)), int(m.group(3)))
    return (None, 0, 0)


def topic_dirs(base):
    return sorted(d for d in glob.glob(os.path.join(base, "topics", "*")) if os.path.isdir(d))


def build():
    L = ["# Research watch — master index", "",
         "*Generated by `build_research_index.py`. Do not edit by hand — edits are overwritten.*", "",
         "One row per program with its last refresh and source count, then the ten topics under each. See "
         "[`README.md`](README.md) for how the watch works and [`CHANGELOG.md`](CHANGELOG.md) for the history "
         "of what each run caught.", "",
         "## Programs", "", "| program | last run | sources | topics |", "|---|---|---|---|"]
    total = 0
    for p in PROGRAMS:
        base = os.path.join(HERE, p)
        run, _src, _ver = meta(os.path.join(base, "literature", "deep_research_report.md"))
        nbib = count_bib(os.path.join(base, "literature", "references.bib"))
        ntopics = len(topic_dirs(base))
        total += nbib
        L.append(f"| [{p}]({p}/README.md) | {run or '—'} | {nbib} | {ntopics} |")
    L += ["", f"**Total program-level bibliography: {total} entries across {len(PROGRAMS)} programs.**", ""]

    for p in PROGRAMS:
        base = os.path.join(HERE, p)
        title = first_heading(os.path.join(base, "README.md")) or p
        L += [f"## {title}", "",
              f"[`{p}/REVIEW.md`]({p}/REVIEW.md) · "
              f"[`literature/references.bib`]({p}/literature/references.bib)", ""]
        tdirs = topic_dirs(base)
        if not tdirs:
            L += ["*topics pending the program-level research*", ""]
            continue
        L += ["| # | topic | sources |", "|---|---|---|"]
        for d in tdirs:
            name = os.path.basename(d)
            num = name.split("_")[0]
            ttitle = first_heading(os.path.join(d, "REVIEW.md")) or name.split("_", 1)[-1].replace("_", " ")
            nb = count_bib(os.path.join(d, "references.bib"))
            L.append(f"| {num} | [{ttitle}]({p}/topics/{name}/REVIEW.md) | {nb} |")
        L.append("")
    return "\n".join(L).rstrip() + "\n"


def main():
    out = os.path.join(HERE, "INDEX.md")
    content = build()
    if "--check" in sys.argv:
        existing = open(out).read() if os.path.exists(out) else ""
        if existing != content:
            print("research INDEX.md is stale — run build_research_index.py")
            sys.exit(1)
        print("research INDEX.md is up to date.")
        return
    with open(out, "w") as f:
        f.write(content)
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
